//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream breakSound {
            get {
                return ResourceManager.GetStream("breakSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cobbleBrick_1hit {
            get {
                object obj = ResourceManager.GetObject("cobbleBrick_1hit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cobbleBrick_2hits {
            get {
                object obj = ResourceManager.GetObject("cobbleBrick_2hits", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cobbleBrick_3hits {
            get {
                object obj = ResourceManager.GetObject("cobbleBrick_3hits", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;65&lt;/x&gt;
        ///    &lt;y&gt;26&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;175&lt;/x&gt;
        ///    &lt;y&gt;26&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;285&lt;/x&gt;
        ///    &lt;y&gt;26&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;395&lt;/x&gt;
        ///    &lt;y&gt;26&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;505&lt;/x&gt;
        ///    &lt;y&gt;26&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;615&lt;/x&gt;
        ///    &lt;y&gt;26&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;725&lt;/x&gt;
        ///    &lt;y&gt;26&lt;/y&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;364&lt;/x&gt;
        ///    &lt;y&gt;7&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///    &lt;colour&gt;Red&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;288&lt;/x&gt;
        ///    &lt;y&gt;38&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///    &lt;colour&gt;Red&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;440&lt;/x&gt;
        ///    &lt;y&gt;38&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///    &lt;colour&gt;Red&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;212&lt;/x&gt;
        ///    &lt;y&gt;69&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///    &lt;colour&gt;Red&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;516&lt;/x&gt;
        ///    &lt;y&gt;69&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///    &lt;colour&gt;Red&lt;/colo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level2 {
            get {
                return ResourceManager.GetString("level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;163&lt;/x&gt;
        ///    &lt;y&gt;56&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///    &lt;colour&gt;DarkOrange&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;275&lt;/x&gt;
        ///    &lt;y&gt;56&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///    &lt;colour&gt;DarkOrange&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;499&lt;/x&gt;
        ///    &lt;y&gt;56&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///    &lt;colour&gt;DarkOrange&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;611&lt;/x&gt;
        ///    &lt;y&gt;56&lt;/y&gt;
        ///    &lt;hp&gt;3&lt;/hp&gt;
        ///    &lt;colour&gt;DarkOrange&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;163&lt;/x&gt;
        ///    &lt;y&gt;90&lt;/y&gt;
        ///    &lt;hp&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level3 {
            get {
                return ResourceManager.GetString("level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;380&lt;/x&gt;
        ///    &lt;y&gt;9&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///    &lt;colour&gt;Red&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;437&lt;/x&gt;
        ///    &lt;y&gt;9&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///    &lt;colour&gt;Red&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;326&lt;/x&gt;
        ///    &lt;y&gt;25&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///    &lt;colour&gt;Red&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;270&lt;/x&gt;
        ///    &lt;y&gt;36&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///    &lt;colour&gt;Red&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;214&lt;/x&gt;
        ///    &lt;y&gt;55&lt;/y&gt;
        ///    &lt;hp&gt;2&lt;/hp&gt;
        ///    &lt;colour&gt;Red&lt;/colou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level4 {
            get {
                return ResourceManager.GetString("level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;12&lt;/x&gt;
        ///    &lt;y&gt;9&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;colour&gt;Maroon&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;77&lt;/x&gt;
        ///    &lt;y&gt;9&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;colour&gt;Maroon&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;724&lt;/x&gt;
        ///    &lt;y&gt;9&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;colour&gt;Maroon&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;792&lt;/x&gt;
        ///    &lt;y&gt;9&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;colour&gt;Maroon&lt;/colour&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;12&lt;/x&gt;
        ///    &lt;y&gt;48&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;colour&gt;Mar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level5 {
            get {
                return ResourceManager.GetString("level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream paddleSound {
            get {
                return ResourceManager.GetStream("paddleSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///.
        /// </summary>
        internal static string ScoreXML {
            get {
                return ResourceManager.GetString("ScoreXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap title_screen_brick_breaker {
            get {
                object obj = ResourceManager.GetObject("title_screen_brick_breaker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream wallSound {
            get {
                return ResourceManager.GetStream("wallSound", resourceCulture);
            }
        }
    }
}
